import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Capacitor } from "@capacitor/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const platform = Capacitor.getPlatform();
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={`layout ${platform}`}>
          {platform === "android" && (
            <header className="android-header">Android Header</header>
          )}
          {platform === "web" && (
            <header className="web-header">Web Header</header>
          )}
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
